# Generated by Django 5.0.1 on 2024-05-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_merchandise_alter_foto_phototype_foto_merchandise'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='punto_acopio',
            field=models.CharField(default='', max_length=255),
        ),
    ]
