# Generated by Django 5.0.1 on 2024-05-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_foto_material_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
